name: Update EPG XMLTV

on:
  schedule:
    - cron: "0 0 * * *"  # Jalankan setiap hari pada pukul 00:00 UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        pip install requests beautifulsoup4 lxml

    - name: Run scraping script
      run: |
        python scrape_to_xmltv.py

    - name: Commit and push changes
      run: |
        git config --local user.name "github-actions[bot]"
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git add epg.xml
        git commit -m "Update EPG XMLTV"
        git push
